name: mi_card
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - images/reb_bluescarf@600px.jpg

  fonts:
  - family: Sacramento-Regular
    fonts:
      - asset: fonts/Sacramento-Regular.ttf
  - family: JosefinSlab-Regular
    fonts:
      - asset: fonts/JosefinSlab-Regular.ttf
  - family: JosefinSlab-Bold
    fonts:
      - asset: fonts/JosefinSlab-Bold.ttf
  - family: JosefinSlab-SemiBold
    fonts:
      - asset: fonts/JosefinSlab-SemiBold.ttf